#!/bin/sh
# inkVerb updater for Inker™, verb.ink

# This updates the Inker
## This contains many version updaters to update a Inker™ sequentially, one version at a time.
## This is run at the path: /var/local/ink/${IUPDATE_REPO}/update

# DEV NOTE: Larger versions must be at the bottom, smaller versions at the top, so "descending"

# DEV INSTRUCTIONS: Put all related files for each patch in a folder named by the version number, ie 0.806


MIN_IVERNO=0.206
IUPDATE_REPO="ink-dev-update"

## Sample version updater:
#UPDATE_PATCH_IVERNO=
#if [ $(echo ${UPDATE_PATCH_IVERNO} | sed -e "s/\.//" | sed -e "s/^0*//") -gt $(echo ${IVERNO} | sed -e "s/\.//" | sed -e "s/^0*//") ] ; then
#
# Move to working directory of the patch
#if [ -d "/var/local/ink/${IUPDATE_REPO}/${UPDATE_PATCH_IVERNO}/" ]; then
#cd /var/local/ink/${IUPDATE_REPO}/${UPDATE_PATCH_IVERNO}/; fi
#
#
## Run the update scripts for this patch
#
###### SCRIPTS GO HERE #####
## NOTE: PWD is /var/local/ink/${IUPDATE_REPO}/${UPDATE_PATCH_IVERNO}/
#
#
############################
## Set and refresh the current version into inklists
#sed -i "s/IVERNO=.*/IVERNO=${UPDATE_PATCH_IVERNO}/g" /var/local/ink/configs/inklists/inkerverno
#. /var/local/ink/configs/inklists/inkerverno
#echo "Inker updated to v${IVERNO}"
#else
#echo "${UPDATE_PATCH_VERNO} patch not necessary..."
#fi
############################


## Version Check ##
### The minimum version that can use this updater
## Include the configs
. /var/local/ink/configs/inklists/inkerverno
. /var/local/ink/configs/inkerinfo
. /var/local/verb/configs/sitenameip
## Check minimal updateable version
if [ $(echo ${MIN_IVERNO} | sed -e "s/\.//" | sed -e "s/^0*//") -gt $(echo ${IVERNO} | sed -e "s/\.//" | sed -e "s/^0*//") ] ; then
echo "Current Verber™ version is ${IVERNO}, minimum ${MIN_IVERNO} to use this updater.
Run updateverberlegacy for older versions."
exit 22
fi

# Update Knights & repoverlist
rm -rf /var/local/ink/knights/*
cp -rf /var/local/ink/${IUPDATE_REPO}/knights/* /var/local/ink/knights/
cp -f /var/local/ink/${IUPDATE_REPO}/repoverlist /var/local/ink/configs/inklists/
echo "Knights and repo list have been updated."

# Run version-by-version updates


UPDATE_PATCH_IVERNO=0.206
if [ $(echo ${UPDATE_PATCH_IVERNO} | sed -e "s/\.//" | sed -e "s/^0*//") -gt $(echo ${IVERNO} | sed -e "s/\.//" | sed -e "s/^0*//") ] ; then

 Move to working directory of the patch
if [ -d "/var/local/verb/${IUPDATE_REPO}/${UPDATE_PATCH_IVERNO}/" ]; then
cd /var/local/verb/${IUPDATE_REPO}/${UPDATE_PATCH_IVERNO}/; fi


# Run the update scripts for this patch

##### SCRIPTS GO HERE #####

echo "Still updating serfs only for v0.206"


###########################
# Set and refresh the current version into inklists
sed -i "s/IVERNO=.*/IVERNO=${UPDATE_PATCH_IVERNO}/g" /var/local/ink/configs/inklists/inkerverno
. /var/local/ink/configs/inklists/inkerverno
echo "Inker updated to v${IVERNO}"
else
echo "${UPDATE_PATCH_VERNO} patch not necessary..."
fi
###########################


# Finish
echo "Inker at v${IVERNO} framework from ${INKUPDATEREPO}."

