#!/bin/sh
#inkVerbKnight! verb.ink
#set -e

# This resets a complete list of a single remote inkDNS verm/domain-mod Verber account's base domain and all it's hosted domain slave records in the Bind9 config file: /var/cache/bind/verbers/named.conf.VERBERACCOUNT.verbacct
## This only processes one, single Verber "name" account, but all domains for its DNS
## Eg, this will set all name.verb.ink, name.verb.emial, name.verb.blue, etc, and other domains (added to this Inker) records, but only for the "name" Verb namespace, also with a domain-mod

# How to use:
## ./inkdnsinkrefreshverber [ Verber type - "verb" or "dmod" ] [ vname OR mod-domain.tld ]

# Eg:
## ./inkdnsinkrefreshverber verb name
## ./inkdnsinkrefreshverber dmod poetryiscode.com


VTYPE="$1"
VNAME="$2"

# Install status
if [ -f "/var/local/ink/conf/inkdns/inkdnsstatus" ]; then
. /var/local/ink/conf/inkdns/inkdnsstatus
  if [ "${INKDNSINKERSTAT}" = "INSTALLED" ]; then

# Account status
if [ ! -d "/var/local/ink/verbers/v.${VTYPE}.${VNAME}" ]; then
echo "The Verber \"${VNAME}\" type \"${VTYPE}\" does not exist. Doing nothing."
exit 0; fi

    # Refresh the inkDNS domain list file
    rm -f /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct
    cp /var/local/ink/conf/inkdns/named.conf.TYPE.ACCOUNT.verbacct /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct
    chown bind:bind /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct

    ## Each verb tld
    . /var/local/ink/verbers/v.${VTYPE}.${VNAME}/nfo.base

    ### IP4 & IP6
    . /var/local/ink/verbers/v.${VTYPE}.${VNAME}/tld.${emailVERBER}
    sed -i "s/verberIP6/${VERBERIPV4}/g" /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct
    sed -i "s/verberIP4/${VERBERIPV6}/g" /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct
    sed -i "s/verberARPAIP4/${VERBERARPAIP4}/g" /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct
    sed -i "s/verberARPAIP6/${VERBERARPAIP6}/g" /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct

    ### email
    . /var/local/ink/verbers/v.${VTYPE}.${VNAME}/tld.${emailVERBER}
    sed -i "s/emaildomainZone/${emailURI}/g" /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct
    sed -i "s/emaildomIP6/${VERBERIPV4}/g" /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct
    sed -i "s/emaildomIP4/${VERBERIPV6}/g" /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct

    ### city
    . /var/local/ink/verbers/v.${VTYPE}.${VNAME}/tld.${cityVERBER}
    sed -i "s/citydomainZone/${cityURI}/g" /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct
    sed -i "s/citydomIP6/${VERBERIPV4}/g" /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct
    sed -i "s/citydomIP4/${VERBERIPV6}/g" /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct

    ### one
    . /var/local/ink/verbers/v.${VTYPE}.${VNAME}/tld.${oneVERBER}
    sed -i "s/onedomainZone/${oneURI}/g" /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct
    sed -i "s/onedomIP6/${VERBERIPV4}/g" /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct
    sed -i "s/onedomIP4/${VERBERIPV6}/g" /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct

    ### ink
    . /var/local/ink/verbers/v.${VTYPE}.${VNAME}/tld.${inkVERBER}
    sed -i "s/inkdomainZone/${inkURI}/g" /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct
    sed -i "s/inkdomIP6/${VERBERIPV4}/g" /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct
    sed -i "s/inkdomIP4/${VERBERIPV6}/g" /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct

    ### blue
    . /var/local/ink/verbers/v.${VTYPE}.${VNAME}/tld.${blueVERBER}
    sed -i "s/bluedomainZone/${blueURI}/g" /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct
    sed -i "s/bluedomIP6/${VERBERIPV4}/g" /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct
    sed -i "s/bluedomIP4/${VERBERIPV6}/g" /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct

    ### vip
    . /var/local/ink/verbers/v.${VTYPE}.${VNAME}/tld.${vipVERBER}
    sed -i "s/vipdomainZone/${vipURI}/g" /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct
    sed -i "s/vipdomIP6/${VERBERIPV4}/g" /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct
    sed -i "s/vipdomIP4/${VERBERIPV6}/g" /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct

    ### kiwi
    . /var/local/ink/verbers/v.${VTYPE}.${VNAME}/tld.${kiwiVERBER}
    sed -i "s/kiwidomainZone/${kiwiURI}/g" /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct
    sed -i "s/kiwidomIP6/${VERBERIPV4}/g" /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct
    sed -i "s/kiwidomIP4/${VERBERIPV6}/g" /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct

    ### cash
    . /var/local/ink/verbers/v.${VTYPE}.${VNAME}/tld.${cashVERBER}
    sed -i "s/cashdomainZone/${cashURI}/g" /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct
    sed -i "s/cashdomIP6/${VERBERIPV4}/g" /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct
    sed -i "s/cashdomIP4/${VERBERIPV6}/g" /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct

    ### pink
    . /var/local/ink/verbers/v.${VTYPE}.${VNAME}/tld.${pinkVERBER}
    sed -i "s/pinkdomainZone/${pinkURI}/g" /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct
    sed -i "s/pinkdomIP6/${VERBERIPV4}/g" /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct
    sed -i "s/pinkdomIP4/${VERBERIPV6}/g" /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct

    ### red
    . /var/local/ink/verbers/v.${VTYPE}.${VNAME}/tld.${redVERBER}
    sed -i "s/reddomainZone/${redURI}/g" /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct
    sed -i "s/reddomIP6/${VERBERIPV4}/g" /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct
    sed -i "s/reddomIP4/${VERBERIPV6}/g" /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct

    ### rocks
    . /var/local/ink/verbers/v.${VTYPE}.${VNAME}/tld.${rocksVERBER}
    sed -i "s/rocksdomainZone/${rocksURI}/g" /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct
    sed -i "s/rocksdomIP6/${VERBERIPV4}/g" /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct
    sed -i "s/rocksdomIP4/${VERBERIPV6}/g" /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct

    ### Wrap-up
    echo "Base Verber records updated for ${VTYPE} ${VNAME}."

    ## Each domain
    cd /var/local/ink/verbers/v.${VTYPE}.${VNAME}
    for domainNFO in domain.*; do
      domainZone="$(echo ${domainNFO} | sed 's/domain\.//' )"
      . /var/local/ink/verbers/v.${VTYPE}.${VNAME}/${domainNFO}
      . /var/local/ink/verbers/v.${VTYPE}.${VNAME}/tld.${verberTLD}
      echo "// ${domainZone}
zone \"${domainZone}\" { type slave; masters { $domIP6; $domIP4; }; file \"/var/cache/bind/zones-inker/db.${domainZone}\"; };
" >> /var/cache/bind/verbers/named.conf.${VTYPE}.${VNAME}.verbacct
    echo "${domainZone} records updated for ${VTYPE} ${VNAME}."
    done

  else echo "inkDNS not installed, run inkdnsinstall first."; exit 0
  fi
else echo "inkDNS not installed, run inkdnsinstall first."; exit 0
fi
