#!/bin/sh
#inkVerbKnight! verb.ink
#set -e

# This resets a complete list of remote inkDNS domains for slave records in the Bind9 config file: /etc/bind/named.conf.verb after copying inkDNS db. files to /etc/bind/zones-inker/inker/db.*

# How to use:
## ./inkdnsinkrefreshbind


# Include the config
. /var/local/verb/conf/sitenameip

if [ -f "/var/local/verb/conf/inkdns/inkdnsstatus" ]; then
. /var/local/verb/conf/inkdns/inkdnsstatus
  if [ "${INKDNSSTAT}" = "INSTALLED" ]; then


    # Create the directories in configs
    rm -rf /etc/bind/zones-inker
    cp -rf /var/local/ink/conf/inkdns/zones-inker /etc/bind/
    chown -R bind:bind /etc/bind/zones-inker
    chmod -R 644 /etc/bind/zones-inker

    # inkDNS domain list file
    rm -f /etc/bind/named.conf.inker
    touch /etc/bind/named.conf.inker
    echo '// inkVerb-inkDNS domain list file, managed automatically, edits will likely be deleted' >> /etc/bind/named.conf.inker
    chown bind:bind /etc/bind/named.conf.inker
    cd /etc/bind/zones-inker/
    for inkZoneDB in db.*; do
      inkZone="$(echo ${inkZoneDB} | sed 's/db\.//' )"
      echo "\"zone \"${inkZone}\" {
type slave;
masters { $CLIENTDNSIP6; };
file \"/etc/bind/zones-inker/db.${inkZone}\";
};

zone \"${SITEARPAIP4}\" {
type slave;
masters { $CLIENTDNSIP6; };
file \"/etc/bind/zones-inker/nv.${inkZone}\";
allow-query { any; };
};

zone \"${SITEARPAIP6}\" {
type slave;
masters { $CLIENTDNSIP6; };
file \"/etc/bind/zones-inker/nv.${inkZone}\";
allow-query { any; };
};

" >> /etc/bind/named.conf.inker
    done
      chown bind:bind /etc/bind/named.conf.inker
      chmod 644 /etc/bind/named.conf.inker
  else echo "inkDNS not installed, run inkdnsinstall first."; exit 0
  fi
else echo "inkDNS not installed, run inkdnsinstall first."; exit 0
fi
