#!/bin/sh
#inkVerbKnight! verb.ink
#set -e

# This resets a complete list of all remote inkDNS Verber accounts for slave records in the Bind9 config file: /var/cache/bind/named.conf.inker

# How to use:
## ./inkdnsinkrefreshinker


if [ -f "/var/local/ink/conf/inkdns/inkdnsstatus" ]; then
. /var/local/ink/conf/inkdns/inkdnsstatus
  if [ "${INKDNSINKERSTAT}" = "INSTALLED" ]; then

    # inkDNS domain list file
    rm -f /var/cache/bind/named.conf.inker
    touch /var/cache/bind/named.conf.inker
    echo '// inkVerb-inkDNS domain list file, managed automatically, edits will likely be deleted' >> /var/cache/bind/named.conf.inker
    chown bind:bind /var/cache/bind/named.conf.inker
    chmod 644 /var/cache/bind/named.conf.inker
    cd /var/cache/bind/verbers
    for namedVAccount in named.conf.*.*.verbacct; do
      echo "include \"/var/cache/bind/verbers/${namedVAccount}\";" >> /var/cache/bind/named.conf.inker
    done
  else echo "inkDNS not installed, run inkdnsinkinstall first."; exit 0
  fi
else echo "inkDNS not installed, run inkdnsinkinstall first."; exit 0
fi
