#!/bin/bash
#inkVerbKnight! verb.ink
#set -e

# This adds a supported Verber to this Inker

# How to use:
## ./verberadd [ vspace name / MOD ] [ main tld ] [ mail tld ] [ IPv4 ] [ IPv6 ] [ domain.tld mod base - OPTIONAL, only if a domain mod ]

# Eg:
## ./verbadd name ink email 555.555.555.555 2008::abcd
## ./verbadd MOD ink email 555.555.555.555.2008::abcd poetryiscode.com


VNAME="$1"
SERVERTLD="$2"
SVMAILTLD="$3"
SERVERIPV4="$4"
SERVERIPV6="$5"
DMODBASE="$6"

# Set the IPv4 for ARPA
SERVERARPAIP4=$(echo ${SERVERIPV4} | sed -r 's/^([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3})$/\4.\3.\2.\1.in-addr.arpa/')

# Set the IPv6 for ARPA
## Expand/Compress
## THANKS https://stackoverflow.com/a/50208987/10343144

### helper to convert hex to dec (portable version)
hex2dec(){
    [ "$1" != "" ] && printf "%d" "$(( 0x$1 ))"
}

### expand an IPv6 address
expand_ipv6() {
    ip=$1

    # prepend 0 if we start with :
    echo $ip | grep -qs "^:" && ip="0${ip}"

    # expand ::
    if echo $ip | grep -qs "::"; then
        colons=$(echo $ip | sed 's/[^:]//g')
        missing=$(echo ":::::::::" | sed "s/$colons//")
        expanded=$(echo $missing | sed 's/:/:0/g')
        ip=$(echo $ip | sed "s/::/$expanded/")
    fi

    blocks=$(echo $ip | grep -o "[0-9a-f]\+")
    set $blocks

    printf "%04x:%04x:%04x:%04x:%04x:%04x:%04x:%04x\n" \
        $(hex2dec $1) \
        $(hex2dec $2) \
        $(hex2dec $3) \
        $(hex2dec $4) \
        $(hex2dec $5) \
        $(hex2dec $6) \
        $(hex2dec $7) \
        $(hex2dec $8)
}

### returns a compressed IPv6 address under the form recommended by RFC5952
compress_ipv6() {
    ip=$1

    blocks=$(echo $ip | grep -o "[0-9a-f]\+")
    set $blocks

    # compress leading zeros
    ip=$(printf "%x:%x:%x:%x:%x:%x:%x:%x\n" \
        $(hex2dec $1) \
        $(hex2dec $2) \
        $(hex2dec $3) \
        $(hex2dec $4) \
        $(hex2dec $5) \
        $(hex2dec $6) \
        $(hex2dec $7) \
        $(hex2dec $8)
    )

    # prepend : for easier matching
    ip=:$ip

    # :: must compress the longest chain
    for pattern in :0:0:0:0:0:0:0:0 \
            :0:0:0:0:0:0:0 \
            :0:0:0:0:0:0 \
            :0:0:0:0:0 \
            :0:0:0:0 \
            :0:0; do
        if echo $ip | grep -qs $pattern; then
            ip=$(echo $ip | sed "s/$pattern/::/")
            # if the substitution occured before the end, we have :::
            ip=$(echo $ip | sed 's/:::/::/')
            break # only one substitution
        fi
    done

    # remove prepending : if necessary
    echo $ip | grep -qs "^:[^:]" && ip=$(echo $ip | sed 's/://')

    echo $ip
}

### reverse expanded IPv6 for ARPA
### THANKS https://stackoverflow.com/a/53674816/10343144
rarpa_ipv6() {
  local idx s=${1//:}
  for (( idx=${#s} - 1; idx>=0; idx-- )); do
    printf '%s.' "${s:$idx:1}"
  done
  printf 'ip6.arpa\n'
}

## Our new variables for the rest
SERVEREXPIP6=$(expand_ipv6 ${SERVERIPV6})
SERVERCMPIP6=$(compress_ipv6 ${SERVERIPV6})
SERVERRARPA6=$(rarpa_ipv6 ${SERVEREXPIP6})


# For domain mod or verb Verber
if [ -n "$6" ] && [ "$1" = "MOD" ]; then
mkdir -p /var/local/ink/verbers/v.dmod.${DMODBASE}
echo "#!/bin/sh
## This is a config file for other verb scripts

# URI list
vNAME=\"${DMODBASE}\"
emailURI=\"email.${DMODBASE}\"
cityURI=\"city.${DMODBASE}\"
oneURI=\"one.${DMODBASE}\"
inkURI=\"ink.${DMODBASE}\"
blueURI=\"blue.${DMODBASE}\"
vipURI=\"vip.${DMODBASE}\"
kiwiURI=\"kiwi.${DMODBASE}\"
cashURI=\"cash.${DMODBASE}\"
pinkURI=\"pink.${DMODBASE}\"
redURI=\"red.${DMODBASE}\"
rocksURI=\"rocks.${DMODBASE}\"

# Hosting Verbers
emailVERBER=\"${SERVERTLD}\"
cityVERBER=\"${SERVERTLD}\"
oneVERBER=\"${SERVERTLD}\"
inkVERBER=\"${SERVERTLD}\"
blueVERBER=\"${SERVERTLD}\"
vipVERBER=\"${SERVERTLD}\"
kiwiVERBER=\"${SERVERTLD}\"
cashVERBER=\"${SERVERTLD}\"
pinkVERBER=\"${SERVERTLD}\"
redVERBER=\"${SERVERTLD}\"
rocksVERBER=\"${SERVERTLD}\"

" > /var/local/ink/verbers/v.dmod.${DMODBASE}/nfo.base

echo "#!/bin/sh
## This is a config file for other verb scripts

nameURI=\"${SERVERTLD}.${DMODBASE}\"
emailTLDURI=\"${SVMAILTLD}.${DMODBASE}\"
VERBERIPV4=\"${SERVERIPV4}\"
VERBERIPV6=\"${SERVERCMPIP6}\"
VERBEREXPIPV6=\"${SERVEREXPIP6}\"
VERBERARPAIP4=\"${SERVERARPAIP4}\"
VERBERARPAIP6=\"${SERVERRARPA6}\"
" > /var/local/ink/verbers/v.dmod.${DMODBASE}/tld.${SERVERTLD}
/var/local/ink/knights/verberstatus verb ${DMODBASE} solo

else

mkdir -p /var/local/ink/verbers/v.verb.${VNAME}
echo "#!/bin/sh
## This is a config file for other verb scripts

# URI list
vNAME=\"${VNAME}\"
emailURI=\"${VNAME}.verb.email\"
cityURI=\"${VNAME}.verb.city\"
oneURI=\"${VNAME}.verb.one\"
inkURI=\"${VNAME}.verb.ink\"
blueURI=\"${VNAME}.verb.blue\"
vipURI=\"${VNAME}.verb.vip\"
kiwiURI=\"${VNAME}.verb.kiwi\"
cashURI=\"${VNAME}.verb.cash\"
pinkURI=\"${VNAME}.verb.pink\"
redURI=\"${VNAME}.verb.red\"
rocksURI=\"${VNAME}.verb.rocks\"

# Hosting Verbers
emailVERBER=\"${SERVERTLD}\"
cityVERBER=\"${SERVERTLD}\"
oneVERBER=\"${SERVERTLD}\"
inkVERBER=\"${SERVERTLD}\"
blueVERBER=\"${SERVERTLD}\"
vipVERBER=\"${SERVERTLD}\"
kiwiVERBER=\"${SERVERTLD}\"
cashVERBER=\"${SERVERTLD}\"
pinkVERBER=\"${SERVERTLD}\"
redVERBER=\"${SERVERTLD}\"
rocksVERBER=\"${SERVERTLD}\"
" > /var/local/ink/verbers/v.verb.${VNAME}/nfo.base

echo "#!/bin/sh
## This is a config file for other verb scripts

nameURI=\"${VNAME}.verb.${SERVERTLD}\"
emailTLDURI=\"${VNAME}.verb.${SVMAILTLD}\"
VERBERIPV4=\"${SERVERIPV4}\"
VERBERIPV6=\"${SERVERCMPIP6}\"
VERBEREXPIPV6=\"${SERVEREXPIP6}\"
VERBERARPAIP4=\"${SERVERARPAIP4}\"
VERBERARPAIP6=\"${SERVERRARPA6}\"
" > /var/local/ink/verbers/v.verb.${VNAME}/tld.${SERVERTLD}
/var/local/ink/knights/verberstatus verb ${VNAME} solo
fi
